#! /usr/bin/env python
# -*- coding: utf-8 -*-

language: python

python:
  - "2.7"
  - "2.6"

install:
  - pip install nose coverage coveralls
  - pip install pyunisend django mock
  - pip install git+git://github.com/ITCase/django-tinymce-4 

script:
  runtest.py 
